public class SampleClass {

    public SampleClass() {
        
    }
    
    public Integer sum() {
        Integer a =5;
        Integer b= 6;
        
        return a + b;
       
    }
    public Integer divide() {
        Integer a =5;
        Integer b= 6;
        
        return a / b;
       
    }
    public Integer multiply() {
        Integer a =5;
        Integer b= 6;
        
        return a * b;
       
    }
    public Integer subtract() {
        Integer a =5;
        Integer b= 6;
        
        return a - b;
       
    }
}
